# Execute (bcs error load custom env file)-> docker compose --env-file .env.db --env-file .env up -d

version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - taskify-postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - ./.env.db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskify-app
    ports:
     - '3000:3000'
    depends_on:
     - db
    # enable this to use traefik
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.taskify.rule=Host(`taskify.${DOMAIN}`)
    #   - traefik.http.routers.taskify.middlewares=redirect-web-to-websecure@internal
    #   - traefik.http.routers.taskify.middlewares=ratelimit-fe@file
    #   - traefik.http.services.taskify.loadbalancer.server.port=3000
    networks:
      - backend
    env_file:
      - ./.env

  pgadmin:
    user: root
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - taskify-postgres-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - ./.env.db

volumes:
  taskify-postgres-data:

networks:
  backend:
    external: true